# 生成 ndarray

生成数组最简单的方式就是使用array函数。array函数接收任意的序列型对象（当然也包括其他的数组），生成一个新的包含传递数据的NumPy数组。例如，列表的转换就是一个好例子：

In [3]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
array1 = np.array(data1)
array1

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列，例如同等长度的列表，将会自动转换成多维数组：

In [4]:
data2 = [[6, 7.5, 8, 0, 1], [61, 17.5, 23, 10, 11]]
array2 = np.array(data2)
array2

array([[ 6. ,  7.5,  8. ,  0. ,  1. ],
       [61. , 17.5, 23. , 10. , 11. ]])

因为data2是一个包含列表的列表，所以Numpy数组arr2形成了二维数组。我们可以通过检查ndim和shape属性来确认这一点：

In [8]:
array2.ndim

2

In [9]:
array2.shape

(2, 5)

除非显式地指定，否则np.array会自动推断生成数组的数据类型。数据类型被存储在一个特殊的元数据dtype中。例如，之前的两个例子：

In [10]:
array1.dtype

dtype('float64')

In [11]:
array2.dtype

dtype('float64')

In [ ]:
显示指定dtype

In [13]:
data3 = [4, 13, 12, 8]
array3 = np.array(data3, dtype="int")
array3

array([ 4, 13, 12,  8])

除了np.array，还有很多其他函数可以创建新数组。例如，给定长度及形状后，zeros可以一次性创造全0数组，ones可以一次性创造全1数组。empty则可以创建一个没有初始化数值的数组。想要创建高维数组，则需要为shape传递一个元组：

In [14]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[1.16735786e-311, 2.91498731e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.16095484e-028]],

       [[6.97283618e+228, 4.61101801e+252],
        [7.26828933e+223, 1.47278596e+179],
        [9.08367237e+223, 1.16466228e-028]]])