# Numpy 常用随机数方法

在python数据分析的学习和应用过程中，经常需要用到numpy的随机函数，由于随机函数random的功能比较多，经常会混淆或记不住，下面我们一起来汇总学习下。

In [2]:
import numpy as np

## numpy.random.rand()

numpy.random.rand(d0,d1,…,dn)

* randn 函数根据给定的维度生成[0, 1]之间的数据，包含0，不包含1
* dn 表示维度
* 返回值为指定维度的 array

In [3]:
np.random.rand(2, 3) # 指定维度为 2行3列

array([[0.53380414, 0.50633967, 0.15955296],
       [0.46639907, 0.69202414, 0.1466259 ]])

## numpy.random.randn()

numpy.random.randn(d0,d1,…,dn)

* 返回一个或者一组样本，具有标准正态分布
* dn 表示维度
* 返回值为指定维度的 array

In [4]:
np.random.randn() # 当没有参数时，返回单个数据

0.771353810273211

In [5]:
np.random.randn(2,4)

array([[-1.54342109,  0.84529908, -0.37979896,  1.87400124],
       [ 0.13278796,  0.42778185, -1.60400427, -0.39082434]])

In [6]:
np.random.randn(4,3,2)

array([[[-0.32673219, -0.74658277],
        [ 0.58282033, -0.7135313 ],
        [ 0.9743897 ,  0.41999398]],

       [[-0.84906191,  0.86692579],
        [ 1.55709009,  2.07073826],
        [-1.29139565, -0.81340372]],

       [[ 0.04850362,  0.03873075],
        [ 0.09877068,  1.72813399],
        [-0.44916004, -0.81887483]],

       [[ 0.849136  ,  2.00678484],
        [-0.3550484 , -0.06840407],
        [ 1.85158055, -0.78324139]]])

标准正态分布介绍：
1. 标准正态分布—-standard normal distribution
2. 标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N（0，1）。

## numpy.random.randint()

numpy.random.randint(low, high=None, size=None, dtype=’l)

* 返回随机整数，范围区间为low-high，包含low，不包含high
* 最小值为low，最大值为high，size 为数组维度，dtype 为数据类型，默认的数据类型是np.int
* high 没有填写时，范围默认为 [0, low]


In [7]:
np.random.randint(1,size=5) # 返回[0,1)之间的整数，所以只有0

array([0, 0, 0, 0, 0])

In [8]:
np.random.randint(1,5) # 返回1个[1,5)时间的随机整数

1

In [9]:
np.random.randint(-5,5,size=(2,2))

array([[ 2,  4],
       [-2,  1]])

## 生成[0,1)之间的浮点数

* numpy.random.random_sample(size=None)
* numpy.random.random(size=None)
* numpy.random.ranf(size=None)
* numpy.random.sample(size=None)

In [10]:
print('-----------random_sample--------------')
print(np.random.random_sample(size=(2,2)))
print('-----------random--------------')
print(np.random.random(size=(2,2)))
print('-----------ranf--------------')
print(np.random.ranf(size=(2,2)))
print('-----------sample--------------')
print(np.random.sample(size=(2,2)))

-----------random_sample--------------
[[0.84209133 0.71201054]
 [0.55310936 0.01834124]]
-----------random--------------
[[0.97952937 0.68329834]
 [0.05406889 0.60493494]]
-----------ranf--------------
[[0.9074233  0.48377082]
 [0.55132857 0.09061453]]
-----------sample--------------
[[0.42614357 0.39320096]
 [0.61476197 0.09163446]]


## numpy.random.choice()

numpy.random.choice(a, size=None, replace=True, p=None)

* 从给定的一维数组中生成随机数
* 参数： a为一维数组类似数据或整数；size为数组维度；p为数组中的数据出现的概率
* a为整数时，对应的一维数组为np.arange(a)

In [11]:
np.random.choice(5,3)

array([3, 3, 0])